import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import localFont from 'next/font/local';
import Loader from "@/components/Pages/Loading/Loading";
import ScrollToTopProgress from "@/components/Scroll/Scroll";

// Configure the font with its source files, weights, and styles
const danaFont = localFont({
  src: [
    {
      path: '../../public/fonts/dana-regular.woff',
      weight: '400', // Specify weight for regular font
      style: 'normal',
    },
    {
      path: '../../public/fonts/dana-regular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-dana',
  
});
const yekanFont = localFont({
  src: [
    {
      path: '../../public/fonts/YekanBakh-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/YekanBakh-Bold.woff',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-yekan',
  
});

export const metadata: Metadata = {
  title: "WebDesignBySina",
  description: "Generated by Creative Components from nextjs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <html lang="fa" dir="rtl" suppressHydrationWarning className={`${danaFont.variable} ${yekanFont.variable}`}>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Loader text="gnidaoL" />
            <ScrollToTopProgress />
            {children}
          </ThemeProvider>
        </body>
      </html>
  );
}
